version: '3.1'
services:
  db:
    build: ./db
    container_name: simplejavaweb_db
    restart: unless-stopped
    env_file:
        - ./db.env
#    environment:
#      MYSQL_ROOT_PASSWORD: example

  app:
    build: ./app
    restart: unless-stopped
    container_name: simplejavaweb_app
    ports:
      - 8080:8080
    env_file:
      - ./app.env
    links:
      - db:mysql
